name: epomaker-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - click
  - hidapi
  - pillow
  - pip
  - pip:
      - click==8.1.7
      - hidapi==0.14.0
      - opencv-python-headless==4.10.0.82
